version: '3.7'

services: 
  database:
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
  server:
    build: 
      context: ./backEnd/
    environment:
      DATABASE_SERVER_NAME: database
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_DATABASE_NAME: viikkobiitsi
      ADMIN_UI_DOMAIN: http://localhost:3001
    ports:
      - 8081:80
    volumes:
      - ./backEnd/PHP:/var/www/html/
  admin-front-end:
    build: 
      context: ./adminUI/
      args:
        REACT_APP_API_URL_ARG: http://localhost:8081/
    ports:
        - 3001:80