name: Build back-end
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the image
        run: docker build ./backEnd --file server.Dockerfile --tag poytiis/viikkobiitsi-backend

      - name: Push the image
        run: |
          docker login -u poytiis -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push poytiis/viikkobiitsi-backend